---
- hosts: all
  become: yes
  tasks:
  - name: update sshd config
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: 'AcceptEnv XMODIFIERS'
      line: 'AllowUsers root test user'
    notify: restart_sshd

  handlers:
  - name: restart_sshd
    service:
      name: sshd
      state: restarted
